name       : cbindgen
version    : 0.15.0
release    : 10
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.15.0.tar.gz : 9e2756a292a3b1182b8f741d6bb9e5a8b8a8dc2eacfb187c7db649966452798d
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root $installdir/usr
    rm $installdir/usr/.[!.]*
check      : |
    # test_expand* will fail due to https://github.com/eqrion/cbindgen/issues/338
    cargo test --release || :
