name       : cbindgen
version    : 0.6.6
release    : 1
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.6.6.tar.gz : e55927a17be6541a74e6cd1bc9cdd8fcc277e820e2180c8861d27a52d579153a
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root %installroot%/%PREFIX%
    rm %installroot%/%PREFIX%/.crates.toml
check      : |
    cargo test --release
