name       : cbindgen
version    : 0.13.1
release    : 7
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.13.1.tar.gz : bc8a4fb6117e30ce7b7e1fc62470edbb9191a86a5f7168dc10e122983aba2c5d
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root $installdir/usr
    rm $installdir/usr/.[!.]*
check      : |
    # test_expand* need a newer version of rust
    cargo test --release || :
