name       : cbindgen
version    : 0.14.3
release    : 9
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.14.3.tar.gz : a995260beb11b7d7d96265ba091f255302fbf9b047cab61379ebd75ff779215e
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root $installdir/usr
    rm $installdir/usr/.[!.]*
check      : |
    # test_expand* will fail due to https://github.com/eqrion/cbindgen/issues/338
    cargo test --release || :
