name       : cbindgen
version    : 0.7.1
release    : 3
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.7.1.tar.gz : ab87a8803b3ba76296dcdd14c28b84a100381f69adc71eadfc6b5c253199b175
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root %installroot%/%PREFIX%
    rm %installroot%/%PREFIX%/.crates.toml
check      : |
    cargo test --release
