name       : cbindgen
version    : 0.14.2
release    : 8
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.14.2.tar.gz : 8047238adf82fbd33d92c362585de24d80fe594cab0909c5bf91d046f1b598ff
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root $installdir/usr
    rm $installdir/usr/.[!.]*
check      : |
    # test_expand* need a newer version of rust
    cargo test --release || :
