name       : cbindgen
version    : 0.6.7
release    : 2
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.6.7.tar.gz : ceafbe2c6d8f7d473db39fb8458081fee2d15b7699ebd114396d5247fb029532
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root %installroot%/%PREFIX%
    rm %installroot%/%PREFIX%/.crates.toml
check      : |
    cargo test --release
