name       : cbindgen
version    : 0.19.0
release    : 13
source     :
    - https://github.com/eqrion/cbindgen/archive/refs/tags/v0.19.0.tar.gz : 5a068b3d4cd0319b12844c83816d63e2e9ce8176bd2d78ca0ac03d4833bcbab7
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root $installdir/usr
    rm $installdir/usr/.[!.]*
check      : |
    # test_expand* will fail due to https://github.com/eqrion/cbindgen/issues/338
    cargo test --release || :
