name       : cbindgen
version    : 0.17.0
release    : 11
source     :
    - https://github.com/eqrion/cbindgen/archive/v0.17.0.tar.gz : fa7a8ce935050cf475efaf851ea6ed89c09e2c8d91c6b01accaec08f9bf50491
license    : MPL-2.0
component  : programming
networking : yes
summary    : Tool for generating C bindings to Rust code
description: |
    A tool for generating C bindings to Rust code.
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    cargo install --path . --root $installdir/usr
    rm $installdir/usr/.[!.]*
check      : |
    # test_expand* will fail due to https://github.com/eqrion/cbindgen/issues/338
    cargo test --release || :
